name: Build and Push Docker Images

on:
  push:
    branches:
      - review-3  
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/Dockerfile  
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/film-react-nest/sp16_backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sp16_frontend:latest

      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sp16_server:latest
